82 feature request suggestion create GitHub actions workflow for automating the build and deployments for feature branches
refactor-group/refactor-platform-rs pull request #87
Opened 2024-12-13 19:14 UTC by lmcdonough

This pull request introduces a new GitHub Actions workflow to build and deploy Docker containers for Rust and Next.js projects. The workflow includes steps for building, testing, and pushing Docker images to the GitHub Container Registry.

#### GitHub Issue: [Closes] #82 

### Changes
* Added a new Github Actions workflow configuration file `.github/workflows/build_and_deploy_containers.yml` to automate the build and deployment process for feature branches and pull requests to the main branch.
* Defined two main jobs: `build_test_run` for building and testing the project, and `build_and_push_docker` for building and pushing Docker images. The latter job depends on the successful completion of the former.
* Configured steps to checkout the repository, install the Rust toolchain, use cached dependencies, install `seaORM CLI`, build the project, and run tests.
* Configured steps to checkout the repository, log in to the GitHub Container Registry, set up Docker Buildx, cache Docker layers, and build and push Docker images for both the Rust backend and the Next.js frontend.
* Implemented a caching mechanism for Docker layers to optimize the build process, including steps## Description

### Testing Strategy
* Manually use the `workflow_dispatch` to iterate and view any errors from the workflow run.

### Concerns
* Managing environment variables, and secrets can be improved upon in the future.

2025-02-16 00:57 UTC, jhodapp commented on Cargo.toml
> +libsqlite3-sys = "0.30.0"                                            # or "0.31.0"
@lmcdonough We don't use sqlite in our backend, is there something that's calling for this from the GitHub builder?

2025-02-16 00:59 UTC, jhodapp commented on entity/Cargo.toml
> +axum-login = "0.17.0"
@lmcdonough I don't recommend updating these packages in this PR as they're not related to what you're trying to accomplish here. We need to be able to test the backend when making these version updates, so it's best to do that as a separate PR.

2025-02-21 19:16 UTC, lmcdonough commented on entity/Cargo.toml
> +axum-login = "0.17.0"
Agreed, I will revert this to 0.16.0

2025-03-06 21:35 UTC, lmcdonough commented on Cargo.toml
> +libsqlite3-sys = "0.30.0"                                            # or "0.31.0"
yep, removed it.

2025-04-11 23:32 UTC, jhodapp requested changes
Thanks Levi, a couple more changes requested.

2025-04-11 23:32 UTC, jhodapp commented on docker-compose.yaml
> +    container_name: ${CONTAINER_NAME}
```suggestion
    container_name: ${BACKEND_CONTAINER_NAME}
```

2025-04-11 23:32 UTC, jhodapp commented on docs/runbooks/Container-README.md
> +    cp .env.example .env
I don't see a .env.example file here in the docs directory, can you please add one that includes all of the necessary environment variables set to real values that work?

2025-04-12 21:48 UTC, jhodapp requested changes

2025-04-12 21:48 UTC, jhodapp commented on docs/runbooks/Container-README.md
> +TIPTAP_JWT_SIGNING_KEY="0f38cb0650a8fc262258ad415f25c52579bfc4095b222f486557d24c8fafaeb8"                                      # JWT signing key for TipTap
@lmcdonough Please remove these keys and the URL. You can use empty strings here.

2025-04-20 21:47 UTC, lmcdonough commented on docs/runbooks/Container-README.md
> +TIPTAP_JWT_SIGNING_KEY="0f38cb0650a8fc262258ad415f25c52579bfc4095b222f486557d24c8fafaeb8"                                      # JWT signing key for TipTap
👍

2025-04-23 15:10 UTC, jhodapp approved these changes
Looks really great Levi, thank you for carrying this all the way.

2025-04-23 18:59 UTC, merged